
public enum Country {
    AFGHANISTAN("Afghan"),
    ALBANIA("Albanian"),
    ALGERIA("Algerian"),
    ARGENTINA("Argentinian"),
    AUSTRALIA("Australian"),
    AUSTRIA("Austrian"),
    BANGLADESH("Bangladeshi"),
    BELGIUM("Belgian"),
    BOLIVIA("Bolivian"),
    BOTSWANA("Batswana"),
    BRAZIL("Brazilian"),
    BULGARIA("Bulgarian"),
    CAMBODIA("Cambodian"),
    CAMEROON("Cameroonian"),
    CANADA("Canadian"),
    CHILE("Chilean"),
    CHINA("Chinese"),
    COLOMBIA("Colombian"),
    COSTA_RICA("Costa Rican"),
    CROATIA("Croatian"),
    CUBA("Cuban"),
    CZECH_REPUBLIC("Czech"),
    DENMARK("Danish"),
    DOMINICAN_REPUBLIC("Dominican"),
    ECUADOR("Ecuadorian"),
    EGYPT("Egyptian"),
    EL_SALVADOR("Salvadorian"),
    ENGLAND("English"),
    ESTONIA("Estonian"),
    ETHIOPIA("Ethiopian"),
    FIJI("Fijian"),
    FINLAND("Finnish"),
    FRANCE("French"),
    GERMANY("German"),
    GHANA("Ghanaian"),
    GREECE("Greek"),
    GUATEMALA("Guatemalan"),
    HAITI("Haitian"),
    HONDURAS("Honduran"),
    HUNGARY("Hungarian"),
    ICELAND("Icelandic"),
    INDIA("Indian"),
    INDONESIA("Indonesian"),
    IRAN("Iranian"),
    IRAQ("Iraqi"),
    IRELAND("Irish"),
    ISRAEL("Israeli"),
    ITALY("Italian"),
    JAMAICA("Jamaican"),
    JAPAN("Japanese"),
    JORDAN("Jordanian"),
    KENYA("Kenyan"),
    KUWAIT("Kuwaiti"),
    LAOS("Lao"),
    LATVIA("Latvian"),
    LEBANON("Lebanese"),
    LIBYA("Libyan"),
    LITHUANIA("Lithuanian"),
    MALAYSIA("Malaysian"),
    MALI("Malian"),
    MALTA("Maltese"),
    MEXICO("Mexican"),
    MONGOLIA("Mongolian"),
    MOROCCO("Moroccan"),
    MOZAMBIQUE("Mozambican"),
    NAMIBIA("Namibian"),
    NEPAL("Nepalese"),
    NETHERLANDS("Dutch"),
    NEW_ZEALAND("New Zealand"),
    NICARAGUA("Nicaraguan"),
    NIGERIA("Nigerian"),
    NORWAY("Norwegian"),
    PAKISTAN("Pakistani"),
    PANAMA("Panamanian"),
    PARAGUAY("Paraguayan"),
    PERU("Peruvian"),
    PHILIPPINES("Philippine"),
    POLAND("Polish"),
    PORTUGAL("Portuguese"),
    ROMANIA("Romanian"),
    RUSSIA("Russian"),
    SAUDI_ARABIA("Saudi"),
    SCOTLAND("Scottish"),
    SENEGAL("Senegalese"),
    SERBIA("Serbian"),
    SINGAPORE("Singaporean"),
    SLOVAKIA("Slovak"),
    SOUTH_AFRICA("South African"),
    SOUTH_KOREA("Korean"),
    SPAIN("Spanish"),
    SRI_LANKA("Sri Lankan"),
    SUDAN("Sudanese"),
    SWEDEN("Swedish"),
    SWITZERLAND("Swiss"),
    SYRIA("Syrian"),
    TAIWAN("Taiwanese"),
    TAJIKISTAN("Tajikistani"),
    THAILAND("Thai"),
    TONGA("Tongan"),
    TUNISIA("Tunisian"),
    TURKEY("Turkish"),
    UKRAINE("Ukrainian"),
    UNITED_ARAB_EMIRATES("Emirati"),
    UNITED_STATES("American"),
    URUGUAY("Uruguayan"),
    VENEZUELA("Venezuelan"),
    VIETNAM("Vietnamese"),
    WALES("Welsh"),
    ZAMBIA("Zambian"),
    ZIMBABWE("Zimbabwean");
 
    private String nationality;
 
    Country(String nationality) {
        this.nationality = nationality;
    }
 
    public String getNationality() {
        return nationality;
    }
}